### ISSUE TITLE
compañias embaucadoras 

### ISSUE THREAD

**Issue by bialikover** [tnstatus/tnstatus#13]
- informar de las compañías están aprovechándose de este tipo de visa para tenerte en benching y venderte al mejor precio (es ilegal si aplicaste con TN) 
- black list de llc que sigan está practica. ( no se dejen embaucar )

**Comment by MexicanHacker** [comment]
Hola @bialikover creo si es buena idea iniciar una lista de compañías con malas prácticas y sugerencias para no dejarse llevar por trampas pero me gustaría quitarle la referencia a la gente y compañías de India debido a que creo que aplica para cualquier empresa que siga estas mañas. ¿Estas de acuerdo?

**Comment by MexicanHacker** [comment]
Quitando referencia a un país en especifico pero dejando el problema en general

**Comment by oliviabasurto** [comment]
Las compañias en EEUU tienen que cumplir requisitos para hacerme una oferta de trabajo ??  tengo  un amigo  que tiene una compañía que hace inspección a los sistemas Anti incendio de los restaurantes, pero no sabemos si su oferta de trabajo nos sirva  para hacer el trámite de una TN .  AYUDA PORFA
