### ISSUE TITLE
Mover la información de Pollero a una wiki

### ISSUE THREAD

**Issue by MexicanHacker** [tnstatus/tnstatus#22]
La información de pollero ya está excediendo el tamaño ideal para una sóla página de markdown. ¿Alguién en contra de moverlo a una wiki?

**Comment by jeduan** [comment]
Yo digo que lo movamos a varios markdowns

Lo que no me gusta de los wikis es que no aparecen inmediatamente. Según lo que he visto son un poco más confusos que el Markdown directo.

**Comment by solojavier** [comment]
Estoy de acuerdo con @jeduan ... Y si lo movemos a un generado de sitios tipo jekyll para que ademas de estructurarlo en varios archivos tenga una mejor presentación?

**Comment by danvalencia** [comment]
+1 @solojavier pero no necesitamos un poco más de contenido primero ?

**Comment by solojavier** [comment]
> La información de pollero ya está excediendo el tamaño ideal para una sóla página de markdown.

**Comment by danvalencia** [comment]
:smile:

**Comment by solojavier** [comment]
¿Que les parece que le ponemos en github pages para empezar?

https://pages.github.com/

Si alguien me puede dar acceso al repositorio puedo hacer una prueba (para no tener que hacer fork y pull request)

**Comment by solojavier** [comment]
@MexicanHacker con tnstatus.com ya podemos cerrar este issue no?

**Comment by MexicanHacker** [comment]
tnstatus.com habilitado con github pages.
